import { collection, getDocs, onSnapshot, query, where } from "firebase/firestore";
import { httpsCallable } from "firebase/functions";
import { db, functions } from "@/lib/firebase";
import { assets } from "@/data/assets";
import { demoState, getDemoSession, saveDemoState } from "@/services/demoService";
import type { Asset, MarketPrice, PriceHistoryPoint, Transaction, UserSettings, Watchlist } from "@/types/dashboard";

const bucket = () => Math.floor(Date.now() / (4 * 60 * 60 * 1000));
const seeded = (text: string) => { let value = 0; for (const char of text) value = (value * 31 + char.charCodeAt(0)) % 100000; return value / 100000; };
const volatility = (asset: Asset) => asset.category === "kripto" ? .05 : asset.category === "saham" ? .02 : .01;
const simulated = (asset: Asset, at = bucket()) => { let factor = .8; for (let i = 0; i <= Math.min(60, at % 365); i += 1) factor *= 1 + (seeded(`${asset.id}:${at - i}`) - .5) * 2 * volatility(asset); return Math.max(1, Math.round(asset.basePrice * factor)); };
type RemotePrice = { price?: number; previousPrice?: number; changePercent?: number; updatedAt?: { toDate?: () => Date } };
export async function getMarketPrices(): Promise<Record<string, MarketPrice>> { let remote = new Map<string, RemotePrice>(); try { const snap = await getDocs(collection(db, "marketPrices")); remote = new Map(snap.docs.map((row) => [row.id, row.data() as RemotePrice])); } catch { /* fallback */ } return Object.fromEntries(assets.map((asset) => { const row = remote.get(asset.id); const price = Number(row?.price ?? simulated(asset)); const previousPrice = Number(row?.previousPrice ?? simulated(asset, bucket() - 1)); return [asset.id, { assetId: asset.id, price, previousPrice, changePercent: Number(row?.changePercent ?? ((price / previousPrice - 1) * 100).toFixed(2)), updatedAt: row?.updatedAt?.toDate?.() ?? new Date() }]; })); }
export function getHistory(assetId: string): PriceHistoryPoint[] { const asset = assets.find((item) => item.id === assetId) ?? assets[0]; return Array.from({ length: 30 }, (_, index) => { const at = bucket() - 29 + index; return { label: new Date(at * 4 * 60 * 60 * 1000).toLocaleDateString("id-ID", { day: "2-digit", month: "short" }), value: simulated(asset, at), at: new Date(at * 4 * 60 * 60 * 1000) }; }); }
export async function getWatchlist(uid?: string): Promise<Watchlist> { if (getDemoSession()) return { assetIds: demoState().watchlist }; if (!uid) return { assetIds: [] }; try { const snap = await getDocs(query(collection(db, "watchlists"), where("uid", "==", uid))); return { assetIds: (snap.docs[0]?.data()?.assetIds ?? []) as string[] }; } catch { return { assetIds: [] }; } }
export function subscribeWatchlist(uid: string | undefined, onChange: (watchlist: Watchlist) => void) { if (getDemoSession()) { onChange({ assetIds: demoState().watchlist }); return () => undefined; } if (!uid) { onChange({ assetIds: [] }); return () => undefined; } const q = query(collection(db, "watchlists"), where("uid", "==", uid)); return onSnapshot(q, (snapshot) => { const doc = snapshot.docs[0]; onChange({ assetIds: (doc?.data()?.assetIds ?? []) as string[] }); }); }
export async function toggleWatchlist(uid: string | undefined, assetId: string): Promise<Watchlist> { if (getDemoSession()) { const state = demoState(); const assetIds = state.watchlist.includes(assetId) ? state.watchlist.filter((id) => id !== assetId) : [...state.watchlist, assetId]; saveDemoState({ watchlist: assetIds }); return { assetIds }; } if (!uid) throw new Error("Sesi tidak ditemukan."); return (await httpsCallable(functions, "toggleWatchlist")({ assetId })).data as Watchlist; }
export async function trade(uid: string | undefined, asset: Asset, side: "buy" | "sell", quantity: number, price: number) { if (quantity <= 0) throw new Error("Jumlah harus lebih besar dari nol."); if (getDemoSession()) { const state = demoState(); const current = state.holdings.find((holding) => holding.assetId === asset.id); const total = quantity * price; if (side === "buy" && state.balance < total) throw new Error("Saldo demo tidak mencukupi."); if (side === "sell" && (!current || current.quantity < quantity)) throw new Error("Holding tidak mencukupi."); const holdings = [...state.holdings]; if (side === "buy") { if (current) current.quantity += quantity; else holdings.push({ id: asset.id, assetId: asset.id, symbol: asset.symbol, name: asset.name, quantity, price, averageBuy: price, changePercent: 0, color: asset.color }); } else if (current) { current.quantity -= quantity; if (current.quantity <= 0) holdings.splice(holdings.indexOf(current), 1); } const transaction: Transaction = { id: `demo-${Date.now()}`, assetId: asset.id, symbol: asset.symbol, name: asset.name, side, quantity, price, total, status: "completed", createdAt: new Date() }; saveDemoState({ balance: state.balance + (side === "buy" ? -total : total), holdings, transactions: [transaction, ...state.transactions] }); return; } if (!uid) throw new Error("Sesi tidak ditemukan."); await httpsCallable(functions, "executeTrade")({ assetId: asset.id, side, quantity }); }
export async function getTransactions(uid?: string): Promise<Transaction[]> { if (getDemoSession()) return demoState().transactions; if (!uid) return []; const snap = await getDocs(query(collection(db, "transactions"), where("uid", "==", uid))); return snap.docs.map((row) => ({ ...row.data(), id: row.id, createdAt: row.data().createdAt?.toDate?.() ?? new Date() })) as Transaction[]; }
export const defaultSettings: UserSettings = { marketAlerts: true, aiInsights: false, systemNotifications: true, emailDigest: false, analytics: true, personalizedRecommendations: true, portfolioSharing: false };
