import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Search, Star } from "lucide-react";
import PageFrame from "@/components/Dashboard/PageFrame";
import { assets } from "@/data/assets";
import { getMarketPrices, getWatchlist, toggleWatchlist } from "@/services/marketService";
import { auth } from "@/lib/firebase";
import type { AssetCategory, MarketPrice } from "@/types/dashboard";
import { formatPercent, formatRupiah } from "@/utils/formatters";
export default function Market() { const [prices, setPrices] = useState<Record<string, MarketPrice>>({}); const [watchlist, setWatchlist] = useState<string[]>([]); const [search, setSearch] = useState(""); const [category, setCategory] = useState<"all" | AssetCategory>("all"); useEffect(() => { void Promise.all([getMarketPrices(), getWatchlist(auth.currentUser?.uid)]).then(([nextPrices, nextWatchlist]) => { setPrices(nextPrices); setWatchlist(nextWatchlist.assetIds); }); }, []); const rows = useMemo(() => assets.filter((asset) => (category === "all" || asset.category === category) && `${asset.name} ${asset.symbol}`.toLowerCase().includes(search.toLowerCase())), [category, search]); return <PageFrame title="Market" description="Harga simulasi diperbarui otomatis setiap 4 jam."><div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl border border-white/10 bg-[#101b2a] px-3 text-slate-400"><Search size={17}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari aset..." className="w-full bg-transparent py-3 outline-none" /></label><div className="flex gap-2 overflow-x-auto">{(["all", "saham", "kripto", "logam"] as const).map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-xl px-4 py-2 text-sm capitalize ${category === item ? "bg-cyan-400 text-slate-950" : "bg-white/5 text-slate-300"}`}>{item === "all" ? "Semua" : item}</button>)}</div></div><div className="overflow-hidden rounded-2xl border border-white/10 bg-[#101b2a]"><div className="grid grid-cols-[1fr_auto_auto] gap-4 border-b border-white/10 px-4 py-3 text-xs text-slate-400 sm:grid-cols-[1fr_150px_110px_80px]"><span>Aset</span><span>Harga</span><span>24 jam</span><span className="hidden sm:block">Favorit</span></div>{rows.map((asset) => { const price = prices[asset.id]; const watched = watchlist.includes(asset.id); return <div key={asset.id} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 border-b border-white/5 px-4 py-4 last:border-0 sm:grid-cols-[1fr_150px_110px_80px]"><Link to={`/market/${asset.id}`} className="min-w-0"><b className="block truncate text-white">{asset.name}</b><span className="text-xs text-slate-400">{asset.symbol} · {asset.category}</span></Link><b>{formatRupiah(price?.price ?? 0)}</b><span className={price?.changePercent && price.changePercent < 0 ? "text-rose-300" : "text-emerald-300"}>{formatPercent(price?.changePercent ?? 0)}</span><button aria-label="Toggle favorit" onClick={() => void toggleWatchlist(auth.currentUser?.uid, asset.id).then((r) => setWatchlist(r.assetIds))} className={`hidden rounded-lg p-2 sm:block ${watched ? "text-amber-300" : "text-slate-500"}`}><Star size={18} fill={watched ? "currentColor" : "none"}/></button></div>; })}</div></PageFrame>; }
