import { useState } from "react";
import { Bolt, CheckCircle2, History, Layers3, Sparkles, UserRound } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import AuthLayout from "@/components/auth/AuthLayout";
import { AuthField } from "@/components/auth/AuthField";
import { getAuthErrorMessage, signInDemo } from "@/services/authService";
import { createDemoToken } from "@/services/otpService";

const stats = [["Portofolio Demo", "Rp 71,2 juta", Layers3], ["Jumlah Aset", "4 aset", Sparkles], ["Riwayat", "12 bulan", History], ["Kredit AI", "20 pertanyaan", Bolt]] as const;
export default function Demo() { const navigate = useNavigate(); const [nickname, setNickname] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const start = async (event: React.FormEvent) => { event.preventDefault(); if (nickname.trim().length < 2) return setError("Nama panggilan minimal 2 karakter."); setError(""); setLoading(true); try { const { customToken } = await createDemoToken(nickname); await signInDemo(customToken); sessionStorage.setItem("asetkita-demo", JSON.stringify({ nickname: nickname.trim(), isDemo: true })); navigate("/dashboard"); } catch (reason) { setError(getAuthErrorMessage(reason)); } finally { setLoading(false); } }; return <AuthLayout><section className="rounded-[2rem] border border-white/10 bg-[#0B1220]/80 p-6 text-center shadow-[0_0_80px_rgba(34,211,238,.1)] backdrop-blur-xl sm:p-8"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300"><Bolt size={26} /></span><h1 className="mt-5 text-3xl font-semibold text-white">Coba Demo AsetKita</h1><p className="mt-3 text-sm leading-6 text-slate-400">Jelajahi seluruh fitur AsetKita menggunakan akun demo tanpa perlu membuat akun.</p><div className="mt-7 grid grid-cols-2 gap-3 text-left">{stats.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-white/10 bg-[#060B16]/75 p-4"><Icon className="text-cyan-300" size={17} /><p className="mt-3 text-xs text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-white">{value}</p></div>)}</div>{error && <p role="alert" className="mt-5 rounded-xl border border-rose-400/25 bg-rose-400/10 px-4 py-3 text-left text-sm text-rose-200">{error}</p>}<form onSubmit={start} className="mt-6 text-left"><AuthField label="Nama Panggilan" value={nickname} onChange={(event) => setNickname(event.target.value)} placeholder="Contoh: InvestorPro" icon={<UserRound size={17} />} required /><button disabled={loading} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-full bg-cyan-500 px-6 py-3.5 text-sm font-semibold text-slate-950 transition hover:bg-cyan-400 disabled:opacity-60">{loading ? "Menyiapkan demo..." : <><Bolt size={17} /> Masuk ke Demo</>}</button></form><div className="mt-6 space-y-2 text-left text-xs text-slate-400">{["Data demo diatur ulang setiap 24 jam", "Tidak ada uang atau transaksi nyata", "Fitur AI tersedia dalam lingkungan demo"].map((item) => <p key={item}><CheckCircle2 className="mr-2 inline-block text-emerald-300" size={14} />{item}</p>)}</div><p className="mt-7 text-sm text-slate-400">Ingin mulai dengan akun asli? <Link to="/register" className="font-medium text-cyan-300 hover:text-cyan-200">Buat akun</Link></p></section></AuthLayout>; }
